// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1559239434;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__simple__amount_to_input_text_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "amount_to_input_text",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_amount = <f64>::sse_decode(&mut deserializer);
            let api_currency_code = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::amount_to_input_text(
                    api_amount,
                    api_currency_code,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__amount_to_minor_units_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "amount_to_minor_units",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_amount = <f64>::sse_decode(&mut deserializer);
            let api_currency_code = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::amount_to_minor_units(
                    api_amount,
                    api_currency_code,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__settlement__calculate_minimal_settlement_edges_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calculate_minimal_settlement_edges",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_balances =
                <Vec<crate::api::settlement::NetBalance>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok =
                    crate::api::settlement::calculate_minimal_settlement_edges(api_balances)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__settlement__calculate_net_balances_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calculate_net_balances",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_obligations =
                <Vec<crate::api::settlement::SplitObligationRow>>::sse_decode(&mut deserializer);
            let api_payments =
                <Vec<crate::api::settlement::SplitPaymentRow>>::sse_decode(&mut deserializer);
            let api_recorded_settlements =
                <Vec<crate::api::settlement::SettlementEdge>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::settlement::calculate_net_balances(
                    api_obligations,
                    api_payments,
                    api_recorded_settlements,
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__receipt_split__calculate_split_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calculate_split",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_receipt = <crate::api::receipt_split::Receipt>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::receipt_split::calculate_split(api_receipt)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__calculate_split_assigned_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calculate_split_assigned",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_lines =
                <Vec<crate::api::simple::AssignedReceiptLine>>::sse_decode(&mut deserializer);
            let api_participants =
                <Vec<crate::api::simple::ParticipantRef>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::calculate_split_assigned(
                    api_lines,
                    api_participants,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__simple__minor_units_to_amount_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "minor_units_to_amount",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_minor = <i64>::sse_decode(&mut deserializer);
            let api_currency_code = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::minor_units_to_amount(
                    api_minor,
                    api_currency_code,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__validate_bill_payments_sum_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "validate_bill_payments_sum",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_line_totals_minor =
                <Vec<crate::api::simple::LineTotalMinor>>::sse_decode(&mut deserializer);
            let api_payments =
                <Vec<crate::api::simple::DraftPaymentMinor>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::simple::validate_bill_payments_sum(
                    api_line_totals_minor,
                    api_payments,
                )?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::simple::AssignedReceiptLine {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_item = <crate::api::simple::DraftLineItem>::sse_decode(deserializer);
        let mut var_assigneeIds = <Vec<String>>::sse_decode(deserializer);
        return crate::api::simple::AssignedReceiptLine {
            item: var_item,
            assignee_ids: var_assigneeIds,
        };
    }
}

impl SseDecode for crate::api::money::CurrencyAmount {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_amountMinor = <i64>::sse_decode(deserializer);
        let mut var_currencyCode = <String>::sse_decode(deserializer);
        let mut var_scale = <u8>::sse_decode(deserializer);
        return crate::api::money::CurrencyAmount {
            amount_minor: var_amountMinor,
            currency_code: var_currencyCode,
            scale: var_scale,
        };
    }
}

impl SseDecode for crate::api::simple::DraftLineItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_price = <f64>::sse_decode(deserializer);
        let mut var_currencyCode = <String>::sse_decode(deserializer);
        return crate::api::simple::DraftLineItem {
            name: var_name,
            price: var_price,
            currency_code: var_currencyCode,
        };
    }
}

impl SseDecode for crate::api::simple::DraftPaymentMinor {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_participantId = <String>::sse_decode(deserializer);
        let mut var_currencyCode = <String>::sse_decode(deserializer);
        let mut var_amountMinor = <i64>::sse_decode(deserializer);
        return crate::api::simple::DraftPaymentMinor {
            participant_id: var_participantId,
            currency_code: var_currencyCode,
            amount_minor: var_amountMinor,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::simple::LineTotalMinor {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_currencyCode = <String>::sse_decode(deserializer);
        let mut var_amountMinor = <i64>::sse_decode(deserializer);
        return crate::api::simple::LineTotalMinor {
            currency_code: var_currencyCode,
            amount_minor: var_amountMinor,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::simple::AssignedReceiptLine> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::simple::AssignedReceiptLine>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::simple::DraftPaymentMinor> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::simple::DraftPaymentMinor>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::simple::LineTotalMinor> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::simple::LineTotalMinor>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::settlement::NetBalance> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::settlement::NetBalance>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::simple::ParticipantRef> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::simple::ParticipantRef>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::receipt_split::ReceiptItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::receipt_split::ReceiptItem>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::settlement::SettlementEdge> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::settlement::SettlementEdge>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::settlement::SplitObligationRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::settlement::SplitObligationRow>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::settlement::SplitPaymentRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::settlement::SplitPaymentRow>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::simple::SplitResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::simple::SplitResult>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::receipt_split::UserOwedMinor> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::receipt_split::UserOwedMinor>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::settlement::NetBalance {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_participantId = <String>::sse_decode(deserializer);
        let mut var_amountMinor = <i64>::sse_decode(deserializer);
        let mut var_currencyCode = <String>::sse_decode(deserializer);
        return crate::api::settlement::NetBalance {
            participant_id: var_participantId,
            amount_minor: var_amountMinor,
            currency_code: var_currencyCode,
        };
    }
}

impl SseDecode for crate::api::simple::ParticipantRef {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_displayName = <String>::sse_decode(deserializer);
        return crate::api::simple::ParticipantRef {
            id: var_id,
            display_name: var_displayName,
        };
    }
}

impl SseDecode for crate::api::receipt_split::Receipt {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_items = <Vec<crate::api::receipt_split::ReceiptItem>>::sse_decode(deserializer);
        let mut var_tax = <crate::api::money::CurrencyAmount>::sse_decode(deserializer);
        let mut var_tip = <crate::api::money::CurrencyAmount>::sse_decode(deserializer);
        return crate::api::receipt_split::Receipt {
            items: var_items,
            tax: var_tax,
            tip: var_tip,
        };
    }
}

impl SseDecode for crate::api::receipt_split::ReceiptItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_cost = <crate::api::money::CurrencyAmount>::sse_decode(deserializer);
        let mut var_assigneeIds = <Vec<String>>::sse_decode(deserializer);
        return crate::api::receipt_split::ReceiptItem {
            name: var_name,
            cost: var_cost,
            assignee_ids: var_assigneeIds,
        };
    }
}

impl SseDecode for crate::api::settlement::SettlementEdge {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_fromParticipantId = <String>::sse_decode(deserializer);
        let mut var_toParticipantId = <String>::sse_decode(deserializer);
        let mut var_amountMinor = <i64>::sse_decode(deserializer);
        let mut var_currencyCode = <String>::sse_decode(deserializer);
        return crate::api::settlement::SettlementEdge {
            from_participant_id: var_fromParticipantId,
            to_participant_id: var_toParticipantId,
            amount_minor: var_amountMinor,
            currency_code: var_currencyCode,
        };
    }
}

impl SseDecode for crate::api::settlement::SplitObligationRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_transactionId = <String>::sse_decode(deserializer);
        let mut var_owerId = <String>::sse_decode(deserializer);
        let mut var_amountMinor = <i64>::sse_decode(deserializer);
        let mut var_currencyCode = <String>::sse_decode(deserializer);
        return crate::api::settlement::SplitObligationRow {
            transaction_id: var_transactionId,
            ower_id: var_owerId,
            amount_minor: var_amountMinor,
            currency_code: var_currencyCode,
        };
    }
}

impl SseDecode for crate::api::settlement::SplitPaymentRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_transactionId = <String>::sse_decode(deserializer);
        let mut var_payerId = <String>::sse_decode(deserializer);
        let mut var_amountMinor = <i64>::sse_decode(deserializer);
        let mut var_currencyCode = <String>::sse_decode(deserializer);
        return crate::api::settlement::SplitPaymentRow {
            transaction_id: var_transactionId,
            payer_id: var_payerId,
            amount_minor: var_amountMinor,
            currency_code: var_currencyCode,
        };
    }
}

impl SseDecode for crate::api::simple::SplitResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_participantId = <String>::sse_decode(deserializer);
        let mut var_personName = <String>::sse_decode(deserializer);
        let mut var_totalOwed = <f64>::sse_decode(deserializer);
        let mut var_currencyCode = <String>::sse_decode(deserializer);
        return crate::api::simple::SplitResult {
            participant_id: var_participantId,
            person_name: var_personName,
            total_owed: var_totalOwed,
            currency_code: var_currencyCode,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::receipt_split::UserOwedMinor {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_userId = <String>::sse_decode(deserializer);
        let mut var_amountMinor = <i64>::sse_decode(deserializer);
        let mut var_currencyCode = <String>::sse_decode(deserializer);
        let mut var_scale = <u8>::sse_decode(deserializer);
        return crate::api::receipt_split::UserOwedMinor {
            user_id: var_userId,
            amount_minor: var_amountMinor,
            currency_code: var_currencyCode,
            scale: var_scale,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        8 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__simple__amount_to_input_text_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__simple__amount_to_minor_units_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__settlement__calculate_minimal_settlement_edges_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => wire__crate__api__settlement__calculate_net_balances_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__receipt_split__calculate_split_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__simple__calculate_split_assigned_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__simple__minor_units_to_amount_impl(ptr, rust_vec_len, data_len),
        10 => {
            wire__crate__api__simple__validate_bill_payments_sum_impl(ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::AssignedReceiptLine {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.item.into_into_dart().into_dart(),
            self.assignee_ids.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::AssignedReceiptLine
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::AssignedReceiptLine>
    for crate::api::simple::AssignedReceiptLine
{
    fn into_into_dart(self) -> crate::api::simple::AssignedReceiptLine {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::money::CurrencyAmount {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.amount_minor.into_into_dart().into_dart(),
            self.currency_code.into_into_dart().into_dart(),
            self.scale.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::money::CurrencyAmount
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::money::CurrencyAmount>
    for crate::api::money::CurrencyAmount
{
    fn into_into_dart(self) -> crate::api::money::CurrencyAmount {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::DraftLineItem {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.price.into_into_dart().into_dart(),
            self.currency_code.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::DraftLineItem
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::DraftLineItem>
    for crate::api::simple::DraftLineItem
{
    fn into_into_dart(self) -> crate::api::simple::DraftLineItem {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::DraftPaymentMinor {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.participant_id.into_into_dart().into_dart(),
            self.currency_code.into_into_dart().into_dart(),
            self.amount_minor.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::DraftPaymentMinor
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::DraftPaymentMinor>
    for crate::api::simple::DraftPaymentMinor
{
    fn into_into_dart(self) -> crate::api::simple::DraftPaymentMinor {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::LineTotalMinor {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.currency_code.into_into_dart().into_dart(),
            self.amount_minor.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::LineTotalMinor
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::LineTotalMinor>
    for crate::api::simple::LineTotalMinor
{
    fn into_into_dart(self) -> crate::api::simple::LineTotalMinor {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::settlement::NetBalance {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.participant_id.into_into_dart().into_dart(),
            self.amount_minor.into_into_dart().into_dart(),
            self.currency_code.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::settlement::NetBalance
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::settlement::NetBalance>
    for crate::api::settlement::NetBalance
{
    fn into_into_dart(self) -> crate::api::settlement::NetBalance {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::ParticipantRef {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.display_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::ParticipantRef
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::ParticipantRef>
    for crate::api::simple::ParticipantRef
{
    fn into_into_dart(self) -> crate::api::simple::ParticipantRef {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::receipt_split::Receipt {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.items.into_into_dart().into_dart(),
            self.tax.into_into_dart().into_dart(),
            self.tip.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::receipt_split::Receipt
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::receipt_split::Receipt>
    for crate::api::receipt_split::Receipt
{
    fn into_into_dart(self) -> crate::api::receipt_split::Receipt {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::receipt_split::ReceiptItem {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.cost.into_into_dart().into_dart(),
            self.assignee_ids.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::receipt_split::ReceiptItem
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::receipt_split::ReceiptItem>
    for crate::api::receipt_split::ReceiptItem
{
    fn into_into_dart(self) -> crate::api::receipt_split::ReceiptItem {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::settlement::SettlementEdge {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.from_participant_id.into_into_dart().into_dart(),
            self.to_participant_id.into_into_dart().into_dart(),
            self.amount_minor.into_into_dart().into_dart(),
            self.currency_code.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::settlement::SettlementEdge
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::settlement::SettlementEdge>
    for crate::api::settlement::SettlementEdge
{
    fn into_into_dart(self) -> crate::api::settlement::SettlementEdge {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::settlement::SplitObligationRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.transaction_id.into_into_dart().into_dart(),
            self.ower_id.into_into_dart().into_dart(),
            self.amount_minor.into_into_dart().into_dart(),
            self.currency_code.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::settlement::SplitObligationRow
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::settlement::SplitObligationRow>
    for crate::api::settlement::SplitObligationRow
{
    fn into_into_dart(self) -> crate::api::settlement::SplitObligationRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::settlement::SplitPaymentRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.transaction_id.into_into_dart().into_dart(),
            self.payer_id.into_into_dart().into_dart(),
            self.amount_minor.into_into_dart().into_dart(),
            self.currency_code.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::settlement::SplitPaymentRow
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::settlement::SplitPaymentRow>
    for crate::api::settlement::SplitPaymentRow
{
    fn into_into_dart(self) -> crate::api::settlement::SplitPaymentRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::SplitResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.participant_id.into_into_dart().into_dart(),
            self.person_name.into_into_dart().into_dart(),
            self.total_owed.into_into_dart().into_dart(),
            self.currency_code.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::SplitResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::SplitResult>
    for crate::api::simple::SplitResult
{
    fn into_into_dart(self) -> crate::api::simple::SplitResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::receipt_split::UserOwedMinor {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.user_id.into_into_dart().into_dart(),
            self.amount_minor.into_into_dart().into_dart(),
            self.currency_code.into_into_dart().into_dart(),
            self.scale.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::receipt_split::UserOwedMinor
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::receipt_split::UserOwedMinor>
    for crate::api::receipt_split::UserOwedMinor
{
    fn into_into_dart(self) -> crate::api::receipt_split::UserOwedMinor {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::simple::AssignedReceiptLine {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::simple::DraftLineItem>::sse_encode(self.item, serializer);
        <Vec<String>>::sse_encode(self.assignee_ids, serializer);
    }
}

impl SseEncode for crate::api::money::CurrencyAmount {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.amount_minor, serializer);
        <String>::sse_encode(self.currency_code, serializer);
        <u8>::sse_encode(self.scale, serializer);
    }
}

impl SseEncode for crate::api::simple::DraftLineItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <f64>::sse_encode(self.price, serializer);
        <String>::sse_encode(self.currency_code, serializer);
    }
}

impl SseEncode for crate::api::simple::DraftPaymentMinor {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.participant_id, serializer);
        <String>::sse_encode(self.currency_code, serializer);
        <i64>::sse_encode(self.amount_minor, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::simple::LineTotalMinor {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.currency_code, serializer);
        <i64>::sse_encode(self.amount_minor, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::simple::AssignedReceiptLine> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::simple::AssignedReceiptLine>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::simple::DraftPaymentMinor> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::simple::DraftPaymentMinor>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::simple::LineTotalMinor> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::simple::LineTotalMinor>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::settlement::NetBalance> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::settlement::NetBalance>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::simple::ParticipantRef> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::simple::ParticipantRef>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::receipt_split::ReceiptItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::receipt_split::ReceiptItem>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::settlement::SettlementEdge> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::settlement::SettlementEdge>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::settlement::SplitObligationRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::settlement::SplitObligationRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::settlement::SplitPaymentRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::settlement::SplitPaymentRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::simple::SplitResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::simple::SplitResult>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::receipt_split::UserOwedMinor> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::receipt_split::UserOwedMinor>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::settlement::NetBalance {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.participant_id, serializer);
        <i64>::sse_encode(self.amount_minor, serializer);
        <String>::sse_encode(self.currency_code, serializer);
    }
}

impl SseEncode for crate::api::simple::ParticipantRef {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.display_name, serializer);
    }
}

impl SseEncode for crate::api::receipt_split::Receipt {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::receipt_split::ReceiptItem>>::sse_encode(self.items, serializer);
        <crate::api::money::CurrencyAmount>::sse_encode(self.tax, serializer);
        <crate::api::money::CurrencyAmount>::sse_encode(self.tip, serializer);
    }
}

impl SseEncode for crate::api::receipt_split::ReceiptItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <crate::api::money::CurrencyAmount>::sse_encode(self.cost, serializer);
        <Vec<String>>::sse_encode(self.assignee_ids, serializer);
    }
}

impl SseEncode for crate::api::settlement::SettlementEdge {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.from_participant_id, serializer);
        <String>::sse_encode(self.to_participant_id, serializer);
        <i64>::sse_encode(self.amount_minor, serializer);
        <String>::sse_encode(self.currency_code, serializer);
    }
}

impl SseEncode for crate::api::settlement::SplitObligationRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.transaction_id, serializer);
        <String>::sse_encode(self.ower_id, serializer);
        <i64>::sse_encode(self.amount_minor, serializer);
        <String>::sse_encode(self.currency_code, serializer);
    }
}

impl SseEncode for crate::api::settlement::SplitPaymentRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.transaction_id, serializer);
        <String>::sse_encode(self.payer_id, serializer);
        <i64>::sse_encode(self.amount_minor, serializer);
        <String>::sse_encode(self.currency_code, serializer);
    }
}

impl SseEncode for crate::api::simple::SplitResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.participant_id, serializer);
        <String>::sse_encode(self.person_name, serializer);
        <f64>::sse_encode(self.total_owed, serializer);
        <String>::sse_encode(self.currency_code, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::receipt_split::UserOwedMinor {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.user_id, serializer);
        <i64>::sse_encode(self.amount_minor, serializer);
        <String>::sse_encode(self.currency_code, serializer);
        <u8>::sse_encode(self.scale, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
