// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/settlement.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AssignedReceiptLine dco_decode_assigned_receipt_line(dynamic raw);

  @protected
  DraftPaymentMinor dco_decode_draft_payment_minor(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LineTotalMinor dco_decode_line_total_minor(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AssignedReceiptLine> dco_decode_list_assigned_receipt_line(dynamic raw);

  @protected
  List<DraftPaymentMinor> dco_decode_list_draft_payment_minor(dynamic raw);

  @protected
  List<LineTotalMinor> dco_decode_list_line_total_minor(dynamic raw);

  @protected
  List<NetBalance> dco_decode_list_net_balance(dynamic raw);

  @protected
  List<ParticipantRef> dco_decode_list_participant_ref(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SettlementEdge> dco_decode_list_settlement_edge(dynamic raw);

  @protected
  List<SplitResult> dco_decode_list_split_result(dynamic raw);

  @protected
  NetBalance dco_decode_net_balance(dynamic raw);

  @protected
  ParticipantRef dco_decode_participant_ref(dynamic raw);

  @protected
  ReceiptItem dco_decode_receipt_item(dynamic raw);

  @protected
  SettlementEdge dco_decode_settlement_edge(dynamic raw);

  @protected
  SplitResult dco_decode_split_result(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AssignedReceiptLine sse_decode_assigned_receipt_line(
    SseDeserializer deserializer,
  );

  @protected
  DraftPaymentMinor sse_decode_draft_payment_minor(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LineTotalMinor sse_decode_line_total_minor(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AssignedReceiptLine> sse_decode_list_assigned_receipt_line(
    SseDeserializer deserializer,
  );

  @protected
  List<DraftPaymentMinor> sse_decode_list_draft_payment_minor(
    SseDeserializer deserializer,
  );

  @protected
  List<LineTotalMinor> sse_decode_list_line_total_minor(
    SseDeserializer deserializer,
  );

  @protected
  List<NetBalance> sse_decode_list_net_balance(SseDeserializer deserializer);

  @protected
  List<ParticipantRef> sse_decode_list_participant_ref(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SettlementEdge> sse_decode_list_settlement_edge(
    SseDeserializer deserializer,
  );

  @protected
  List<SplitResult> sse_decode_list_split_result(SseDeserializer deserializer);

  @protected
  NetBalance sse_decode_net_balance(SseDeserializer deserializer);

  @protected
  ParticipantRef sse_decode_participant_ref(SseDeserializer deserializer);

  @protected
  ReceiptItem sse_decode_receipt_item(SseDeserializer deserializer);

  @protected
  SettlementEdge sse_decode_settlement_edge(SseDeserializer deserializer);

  @protected
  SplitResult sse_decode_split_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_assigned_receipt_line(
    AssignedReceiptLine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_draft_payment_minor(
    DraftPaymentMinor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_line_total_minor(
    LineTotalMinor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_assigned_receipt_line(
    List<AssignedReceiptLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_draft_payment_minor(
    List<DraftPaymentMinor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_line_total_minor(
    List<LineTotalMinor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_net_balance(
    List<NetBalance> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_participant_ref(
    List<ParticipantRef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_settlement_edge(
    List<SettlementEdge> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_split_result(
    List<SplitResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_net_balance(NetBalance self, SseSerializer serializer);

  @protected
  void sse_encode_participant_ref(
    ParticipantRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_receipt_item(ReceiptItem self, SseSerializer serializer);

  @protected
  void sse_encode_settlement_edge(
    SettlementEdge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_split_result(SplitResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
