// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/money.dart';
import 'api/receipt_split.dart';
import 'api/settlement.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1559239434;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_splitbae',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSimpleAmountToInputText({
    required double amount,
    required String currencyCode,
  });

  PlatformInt64 crateApiSimpleAmountToMinorUnits({
    required double amount,
    required String currencyCode,
  });

  List<SettlementEdge> crateApiSettlementCalculateMinimalSettlementEdges({
    required List<NetBalance> balances,
  });

  List<SettlementEdge> crateApiSettlementCalculateNetBalances({
    required List<SplitObligationRow> obligations,
    required List<SplitPaymentRow> payments,
    required List<SettlementEdge> recordedSettlements,
  });

  List<UserOwedMinor> crateApiReceiptSplitCalculateSplit({
    required Receipt receipt,
  });

  List<SplitResult> crateApiSimpleCalculateSplitAssigned({
    required List<AssignedReceiptLine> lines,
    required List<ParticipantRef> participants,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  double crateApiSimpleMinorUnitsToAmount({
    required PlatformInt64 minor,
    required String currencyCode,
  });

  void crateApiSimpleValidateBillPaymentsSum({
    required List<LineTotalMinor> lineTotalsMinor,
    required List<DraftPaymentMinor> payments,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSimpleAmountToInputText({
    required double amount,
    required String currencyCode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(amount, serializer);
          sse_encode_String(currencyCode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAmountToInputTextConstMeta,
        argValues: [amount, currencyCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAmountToInputTextConstMeta =>
      const TaskConstMeta(
        debugName: "amount_to_input_text",
        argNames: ["amount", "currencyCode"],
      );

  @override
  PlatformInt64 crateApiSimpleAmountToMinorUnits({
    required double amount,
    required String currencyCode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(amount, serializer);
          sse_encode_String(currencyCode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAmountToMinorUnitsConstMeta,
        argValues: [amount, currencyCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAmountToMinorUnitsConstMeta =>
      const TaskConstMeta(
        debugName: "amount_to_minor_units",
        argNames: ["amount", "currencyCode"],
      );

  @override
  List<SettlementEdge> crateApiSettlementCalculateMinimalSettlementEdges({
    required List<NetBalance> balances,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_net_balance(balances, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_settlement_edge,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSettlementCalculateMinimalSettlementEdgesConstMeta,
        argValues: [balances],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSettlementCalculateMinimalSettlementEdgesConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_minimal_settlement_edges",
        argNames: ["balances"],
      );

  @override
  List<SettlementEdge> crateApiSettlementCalculateNetBalances({
    required List<SplitObligationRow> obligations,
    required List<SplitPaymentRow> payments,
    required List<SettlementEdge> recordedSettlements,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_split_obligation_row(obligations, serializer);
          sse_encode_list_split_payment_row(payments, serializer);
          sse_encode_list_settlement_edge(recordedSettlements, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_settlement_edge,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSettlementCalculateNetBalancesConstMeta,
        argValues: [obligations, payments, recordedSettlements],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettlementCalculateNetBalancesConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_net_balances",
        argNames: ["obligations", "payments", "recordedSettlements"],
      );

  @override
  List<UserOwedMinor> crateApiReceiptSplitCalculateSplit({
    required Receipt receipt,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_receipt(receipt, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_user_owed_minor,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReceiptSplitCalculateSplitConstMeta,
        argValues: [receipt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiptSplitCalculateSplitConstMeta =>
      const TaskConstMeta(debugName: "calculate_split", argNames: ["receipt"]);

  @override
  List<SplitResult> crateApiSimpleCalculateSplitAssigned({
    required List<AssignedReceiptLine> lines,
    required List<ParticipantRef> participants,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_assigned_receipt_line(lines, serializer);
          sse_encode_list_participant_ref(participants, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_split_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCalculateSplitAssignedConstMeta,
        argValues: [lines, participants],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCalculateSplitAssignedConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_split_assigned",
        argNames: ["lines", "participants"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  double crateApiSimpleMinorUnitsToAmount({
    required PlatformInt64 minor,
    required String currencyCode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(minor, serializer);
          sse_encode_String(currencyCode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMinorUnitsToAmountConstMeta,
        argValues: [minor, currencyCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMinorUnitsToAmountConstMeta =>
      const TaskConstMeta(
        debugName: "minor_units_to_amount",
        argNames: ["minor", "currencyCode"],
      );

  @override
  void crateApiSimpleValidateBillPaymentsSum({
    required List<LineTotalMinor> lineTotalsMinor,
    required List<DraftPaymentMinor> payments,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_line_total_minor(lineTotalsMinor, serializer);
          sse_encode_list_draft_payment_minor(payments, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleValidateBillPaymentsSumConstMeta,
        argValues: [lineTotalsMinor, payments],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleValidateBillPaymentsSumConstMeta =>
      const TaskConstMeta(
        debugName: "validate_bill_payments_sum",
        argNames: ["lineTotalsMinor", "payments"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AssignedReceiptLine dco_decode_assigned_receipt_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AssignedReceiptLine(
      item: dco_decode_draft_line_item(arr[0]),
      assigneeIds: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  Receipt dco_decode_box_autoadd_receipt(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_receipt(raw);
  }

  @protected
  CurrencyAmount dco_decode_currency_amount(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CurrencyAmount(
      amountMinor: dco_decode_i_64(arr[0]),
      currencyCode: dco_decode_String(arr[1]),
      scale: dco_decode_u_8(arr[2]),
    );
  }

  @protected
  DraftLineItem dco_decode_draft_line_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DraftLineItem(
      name: dco_decode_String(arr[0]),
      price: dco_decode_f_64(arr[1]),
      currencyCode: dco_decode_String(arr[2]),
    );
  }

  @protected
  DraftPaymentMinor dco_decode_draft_payment_minor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DraftPaymentMinor(
      participantId: dco_decode_String(arr[0]),
      currencyCode: dco_decode_String(arr[1]),
      amountMinor: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LineTotalMinor dco_decode_line_total_minor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LineTotalMinor(
      currencyCode: dco_decode_String(arr[0]),
      amountMinor: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AssignedReceiptLine> dco_decode_list_assigned_receipt_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_assigned_receipt_line)
        .toList();
  }

  @protected
  List<DraftPaymentMinor> dco_decode_list_draft_payment_minor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_draft_payment_minor).toList();
  }

  @protected
  List<LineTotalMinor> dco_decode_list_line_total_minor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_line_total_minor).toList();
  }

  @protected
  List<NetBalance> dco_decode_list_net_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_net_balance).toList();
  }

  @protected
  List<ParticipantRef> dco_decode_list_participant_ref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_participant_ref).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ReceiptItem> dco_decode_list_receipt_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_receipt_item).toList();
  }

  @protected
  List<SettlementEdge> dco_decode_list_settlement_edge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_settlement_edge).toList();
  }

  @protected
  List<SplitObligationRow> dco_decode_list_split_obligation_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_split_obligation_row).toList();
  }

  @protected
  List<SplitPaymentRow> dco_decode_list_split_payment_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_split_payment_row).toList();
  }

  @protected
  List<SplitResult> dco_decode_list_split_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_split_result).toList();
  }

  @protected
  List<UserOwedMinor> dco_decode_list_user_owed_minor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_user_owed_minor).toList();
  }

  @protected
  NetBalance dco_decode_net_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NetBalance(
      participantId: dco_decode_String(arr[0]),
      amountMinor: dco_decode_i_64(arr[1]),
      currencyCode: dco_decode_String(arr[2]),
    );
  }

  @protected
  ParticipantRef dco_decode_participant_ref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ParticipantRef(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
    );
  }

  @protected
  Receipt dco_decode_receipt(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Receipt(
      items: dco_decode_list_receipt_item(arr[0]),
      tax: dco_decode_currency_amount(arr[1]),
      tip: dco_decode_currency_amount(arr[2]),
    );
  }

  @protected
  ReceiptItem dco_decode_receipt_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ReceiptItem(
      name: dco_decode_String(arr[0]),
      cost: dco_decode_currency_amount(arr[1]),
      assigneeIds: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  SettlementEdge dco_decode_settlement_edge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SettlementEdge(
      fromParticipantId: dco_decode_String(arr[0]),
      toParticipantId: dco_decode_String(arr[1]),
      amountMinor: dco_decode_i_64(arr[2]),
      currencyCode: dco_decode_String(arr[3]),
    );
  }

  @protected
  SplitObligationRow dco_decode_split_obligation_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SplitObligationRow(
      transactionId: dco_decode_String(arr[0]),
      owerId: dco_decode_String(arr[1]),
      amountMinor: dco_decode_i_64(arr[2]),
      currencyCode: dco_decode_String(arr[3]),
    );
  }

  @protected
  SplitPaymentRow dco_decode_split_payment_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SplitPaymentRow(
      transactionId: dco_decode_String(arr[0]),
      payerId: dco_decode_String(arr[1]),
      amountMinor: dco_decode_i_64(arr[2]),
      currencyCode: dco_decode_String(arr[3]),
    );
  }

  @protected
  SplitResult dco_decode_split_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SplitResult(
      participantId: dco_decode_String(arr[0]),
      personName: dco_decode_String(arr[1]),
      totalOwed: dco_decode_f_64(arr[2]),
      currencyCode: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UserOwedMinor dco_decode_user_owed_minor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return UserOwedMinor(
      userId: dco_decode_String(arr[0]),
      amountMinor: dco_decode_i_64(arr[1]),
      currencyCode: dco_decode_String(arr[2]),
      scale: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AssignedReceiptLine sse_decode_assigned_receipt_line(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_item = sse_decode_draft_line_item(deserializer);
    var var_assigneeIds = sse_decode_list_String(deserializer);
    return AssignedReceiptLine(item: var_item, assigneeIds: var_assigneeIds);
  }

  @protected
  Receipt sse_decode_box_autoadd_receipt(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_receipt(deserializer));
  }

  @protected
  CurrencyAmount sse_decode_currency_amount(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_amountMinor = sse_decode_i_64(deserializer);
    var var_currencyCode = sse_decode_String(deserializer);
    var var_scale = sse_decode_u_8(deserializer);
    return CurrencyAmount(
      amountMinor: var_amountMinor,
      currencyCode: var_currencyCode,
      scale: var_scale,
    );
  }

  @protected
  DraftLineItem sse_decode_draft_line_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_price = sse_decode_f_64(deserializer);
    var var_currencyCode = sse_decode_String(deserializer);
    return DraftLineItem(
      name: var_name,
      price: var_price,
      currencyCode: var_currencyCode,
    );
  }

  @protected
  DraftPaymentMinor sse_decode_draft_payment_minor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_participantId = sse_decode_String(deserializer);
    var var_currencyCode = sse_decode_String(deserializer);
    var var_amountMinor = sse_decode_i_64(deserializer);
    return DraftPaymentMinor(
      participantId: var_participantId,
      currencyCode: var_currencyCode,
      amountMinor: var_amountMinor,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LineTotalMinor sse_decode_line_total_minor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_currencyCode = sse_decode_String(deserializer);
    var var_amountMinor = sse_decode_i_64(deserializer);
    return LineTotalMinor(
      currencyCode: var_currencyCode,
      amountMinor: var_amountMinor,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AssignedReceiptLine> sse_decode_list_assigned_receipt_line(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AssignedReceiptLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_assigned_receipt_line(deserializer));
    }
    return ans_;
  }

  @protected
  List<DraftPaymentMinor> sse_decode_list_draft_payment_minor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DraftPaymentMinor>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_draft_payment_minor(deserializer));
    }
    return ans_;
  }

  @protected
  List<LineTotalMinor> sse_decode_list_line_total_minor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LineTotalMinor>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_line_total_minor(deserializer));
    }
    return ans_;
  }

  @protected
  List<NetBalance> sse_decode_list_net_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NetBalance>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_net_balance(deserializer));
    }
    return ans_;
  }

  @protected
  List<ParticipantRef> sse_decode_list_participant_ref(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ParticipantRef>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_participant_ref(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ReceiptItem> sse_decode_list_receipt_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReceiptItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_receipt_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<SettlementEdge> sse_decode_list_settlement_edge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SettlementEdge>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_settlement_edge(deserializer));
    }
    return ans_;
  }

  @protected
  List<SplitObligationRow> sse_decode_list_split_obligation_row(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SplitObligationRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_split_obligation_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<SplitPaymentRow> sse_decode_list_split_payment_row(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SplitPaymentRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_split_payment_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<SplitResult> sse_decode_list_split_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SplitResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_split_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<UserOwedMinor> sse_decode_list_user_owed_minor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <UserOwedMinor>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_user_owed_minor(deserializer));
    }
    return ans_;
  }

  @protected
  NetBalance sse_decode_net_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_participantId = sse_decode_String(deserializer);
    var var_amountMinor = sse_decode_i_64(deserializer);
    var var_currencyCode = sse_decode_String(deserializer);
    return NetBalance(
      participantId: var_participantId,
      amountMinor: var_amountMinor,
      currencyCode: var_currencyCode,
    );
  }

  @protected
  ParticipantRef sse_decode_participant_ref(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    return ParticipantRef(id: var_id, displayName: var_displayName);
  }

  @protected
  Receipt sse_decode_receipt(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_receipt_item(deserializer);
    var var_tax = sse_decode_currency_amount(deserializer);
    var var_tip = sse_decode_currency_amount(deserializer);
    return Receipt(items: var_items, tax: var_tax, tip: var_tip);
  }

  @protected
  ReceiptItem sse_decode_receipt_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_cost = sse_decode_currency_amount(deserializer);
    var var_assigneeIds = sse_decode_list_String(deserializer);
    return ReceiptItem(
      name: var_name,
      cost: var_cost,
      assigneeIds: var_assigneeIds,
    );
  }

  @protected
  SettlementEdge sse_decode_settlement_edge(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fromParticipantId = sse_decode_String(deserializer);
    var var_toParticipantId = sse_decode_String(deserializer);
    var var_amountMinor = sse_decode_i_64(deserializer);
    var var_currencyCode = sse_decode_String(deserializer);
    return SettlementEdge(
      fromParticipantId: var_fromParticipantId,
      toParticipantId: var_toParticipantId,
      amountMinor: var_amountMinor,
      currencyCode: var_currencyCode,
    );
  }

  @protected
  SplitObligationRow sse_decode_split_obligation_row(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transactionId = sse_decode_String(deserializer);
    var var_owerId = sse_decode_String(deserializer);
    var var_amountMinor = sse_decode_i_64(deserializer);
    var var_currencyCode = sse_decode_String(deserializer);
    return SplitObligationRow(
      transactionId: var_transactionId,
      owerId: var_owerId,
      amountMinor: var_amountMinor,
      currencyCode: var_currencyCode,
    );
  }

  @protected
  SplitPaymentRow sse_decode_split_payment_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transactionId = sse_decode_String(deserializer);
    var var_payerId = sse_decode_String(deserializer);
    var var_amountMinor = sse_decode_i_64(deserializer);
    var var_currencyCode = sse_decode_String(deserializer);
    return SplitPaymentRow(
      transactionId: var_transactionId,
      payerId: var_payerId,
      amountMinor: var_amountMinor,
      currencyCode: var_currencyCode,
    );
  }

  @protected
  SplitResult sse_decode_split_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_participantId = sse_decode_String(deserializer);
    var var_personName = sse_decode_String(deserializer);
    var var_totalOwed = sse_decode_f_64(deserializer);
    var var_currencyCode = sse_decode_String(deserializer);
    return SplitResult(
      participantId: var_participantId,
      personName: var_personName,
      totalOwed: var_totalOwed,
      currencyCode: var_currencyCode,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UserOwedMinor sse_decode_user_owed_minor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_amountMinor = sse_decode_i_64(deserializer);
    var var_currencyCode = sse_decode_String(deserializer);
    var var_scale = sse_decode_u_8(deserializer);
    return UserOwedMinor(
      userId: var_userId,
      amountMinor: var_amountMinor,
      currencyCode: var_currencyCode,
      scale: var_scale,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_assigned_receipt_line(
    AssignedReceiptLine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_draft_line_item(self.item, serializer);
    sse_encode_list_String(self.assigneeIds, serializer);
  }

  @protected
  void sse_encode_box_autoadd_receipt(Receipt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_receipt(self, serializer);
  }

  @protected
  void sse_encode_currency_amount(
    CurrencyAmount self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.amountMinor, serializer);
    sse_encode_String(self.currencyCode, serializer);
    sse_encode_u_8(self.scale, serializer);
  }

  @protected
  void sse_encode_draft_line_item(
    DraftLineItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_f_64(self.price, serializer);
    sse_encode_String(self.currencyCode, serializer);
  }

  @protected
  void sse_encode_draft_payment_minor(
    DraftPaymentMinor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.participantId, serializer);
    sse_encode_String(self.currencyCode, serializer);
    sse_encode_i_64(self.amountMinor, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_line_total_minor(
    LineTotalMinor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.currencyCode, serializer);
    sse_encode_i_64(self.amountMinor, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_assigned_receipt_line(
    List<AssignedReceiptLine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_assigned_receipt_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_draft_payment_minor(
    List<DraftPaymentMinor> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_draft_payment_minor(item, serializer);
    }
  }

  @protected
  void sse_encode_list_line_total_minor(
    List<LineTotalMinor> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_line_total_minor(item, serializer);
    }
  }

  @protected
  void sse_encode_list_net_balance(
    List<NetBalance> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_net_balance(item, serializer);
    }
  }

  @protected
  void sse_encode_list_participant_ref(
    List<ParticipantRef> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_participant_ref(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_receipt_item(
    List<ReceiptItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_receipt_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_settlement_edge(
    List<SettlementEdge> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_settlement_edge(item, serializer);
    }
  }

  @protected
  void sse_encode_list_split_obligation_row(
    List<SplitObligationRow> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_split_obligation_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_split_payment_row(
    List<SplitPaymentRow> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_split_payment_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_split_result(
    List<SplitResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_split_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_user_owed_minor(
    List<UserOwedMinor> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_user_owed_minor(item, serializer);
    }
  }

  @protected
  void sse_encode_net_balance(NetBalance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.participantId, serializer);
    sse_encode_i_64(self.amountMinor, serializer);
    sse_encode_String(self.currencyCode, serializer);
  }

  @protected
  void sse_encode_participant_ref(
    ParticipantRef self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
  }

  @protected
  void sse_encode_receipt(Receipt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_receipt_item(self.items, serializer);
    sse_encode_currency_amount(self.tax, serializer);
    sse_encode_currency_amount(self.tip, serializer);
  }

  @protected
  void sse_encode_receipt_item(ReceiptItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_currency_amount(self.cost, serializer);
    sse_encode_list_String(self.assigneeIds, serializer);
  }

  @protected
  void sse_encode_settlement_edge(
    SettlementEdge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fromParticipantId, serializer);
    sse_encode_String(self.toParticipantId, serializer);
    sse_encode_i_64(self.amountMinor, serializer);
    sse_encode_String(self.currencyCode, serializer);
  }

  @protected
  void sse_encode_split_obligation_row(
    SplitObligationRow self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.transactionId, serializer);
    sse_encode_String(self.owerId, serializer);
    sse_encode_i_64(self.amountMinor, serializer);
    sse_encode_String(self.currencyCode, serializer);
  }

  @protected
  void sse_encode_split_payment_row(
    SplitPaymentRow self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.transactionId, serializer);
    sse_encode_String(self.payerId, serializer);
    sse_encode_i_64(self.amountMinor, serializer);
    sse_encode_String(self.currencyCode, serializer);
  }

  @protected
  void sse_encode_split_result(SplitResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.participantId, serializer);
    sse_encode_String(self.personName, serializer);
    sse_encode_f_64(self.totalOwed, serializer);
    sse_encode_String(self.currencyCode, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user_owed_minor(
    UserOwedMinor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_i_64(self.amountMinor, serializer);
    sse_encode_String(self.currencyCode, serializer);
    sse_encode_u_8(self.scale, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
