// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `expected_minor_scale`, `normalize_currency_code`, `validate_currency_amount`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Canonical amount for storage and Rust-side math. **No `f64` in business logic.**
class CurrencyAmount {
  /// Value in minor units (e.g. USD cents, whole IDR).
  final PlatformInt64 amountMinor;

  /// ISO 4217 alphabetic code (e.g. `USD`, `IDR`).
  final String currencyCode;

  /// ISO 4217 minor-unit exponent: USD/EUR = 2, IDR/JPY/KRW = 0.
  /// Documents how `amount_minor` maps to major units; arithmetic uses minor units only.
  final int scale;

  const CurrencyAmount({
    required this.amountMinor,
    required this.currencyCode,
    required this.scale,
  });

  @override
  int get hashCode =>
      amountMinor.hashCode ^ currencyCode.hashCode ^ scale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CurrencyAmount &&
          runtimeType == other.runtimeType &&
          amountMinor == other.amountMinor &&
          currencyCode == other.currencyCode &&
          scale == other.scale;
}
