// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'money.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `allocate_proportional_first_user_slack`, `build_universe`, `resolve_assignees`, `split_equal_with_remainder_spread`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// Split receipt lines, then allocate **tax** and **tip** separately by each user’s pre-tax subtotal.
///
/// - Line costs: divided equally among **unique** assignees; indivisible remainder goes to the first
///   `r` assignees in lexicographic ID order (`+1` minor each).
/// - Tax / tip: proportional floor by pre-tax weights; **all** rounding slack goes to the
///   lexicographically smallest user ID with positive weight (per product rule: “first user” gets the odd cents).
List<UserOwedMinor> calculateSplit({required Receipt receipt}) =>
    RustLib.instance.api.crateApiReceiptSplitCalculateSplit(receipt: receipt);

class Receipt {
  final List<ReceiptItem> items;
  final CurrencyAmount tax;
  final CurrencyAmount tip;

  const Receipt({required this.items, required this.tax, required this.tip});

  @override
  int get hashCode => items.hashCode ^ tax.hashCode ^ tip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Receipt &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          tax == other.tax &&
          tip == other.tip;
}

/// One purchased line: **equal split** among unique assignees (empty = everyone on the receipt).
class ReceiptItem {
  final String name;
  final CurrencyAmount cost;

  /// Participant IDs. Empty means “split among everyone” (union of IDs that appear on any line).
  final List<String> assigneeIds;

  const ReceiptItem({
    required this.name,
    required this.cost,
    required this.assigneeIds,
  });

  @override
  int get hashCode => name.hashCode ^ cost.hashCode ^ assigneeIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiptItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          cost == other.cost &&
          assigneeIds == other.assigneeIds;
}

/// Per-user total owed (items + share of tax + share of tip), minor units.
class UserOwedMinor {
  final String userId;
  final PlatformInt64 amountMinor;
  final String currencyCode;
  final int scale;

  const UserOwedMinor({
    required this.userId,
    required this.amountMinor,
    required this.currencyCode,
    required this.scale,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      amountMinor.hashCode ^
      currencyCode.hashCode ^
      scale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserOwedMinor &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          amountMinor == other.amountMinor &&
          currencyCode == other.currencyCode &&
          scale == other.scale;
}
