// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `settle_one_currency`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Merge duplicate `(participant, currency)` rows, then run greedy netting per currency.
///
/// Returns `Err` if any currency bucket does not sum to zero (after merge).
List<SettlementEdge> calculateMinimalSettlementEdges({
  required List<NetBalance> balances,
}) => RustLib.instance.api.crateApiSettlementCalculateMinimalSettlementEdges(
  balances: balances,
);

class NetBalance {
  final String participantId;

  /// Net **creditor** position: positive = should receive, negative = should pay.
  final PlatformInt64 amountMinor;
  final String currencyCode;

  const NetBalance({
    required this.participantId,
    required this.amountMinor,
    required this.currencyCode,
  });

  @override
  int get hashCode =>
      participantId.hashCode ^ amountMinor.hashCode ^ currencyCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetBalance &&
          runtimeType == other.runtimeType &&
          participantId == other.participantId &&
          amountMinor == other.amountMinor &&
          currencyCode == other.currencyCode;
}

class SettlementEdge {
  final String fromParticipantId;
  final String toParticipantId;
  final PlatformInt64 amountMinor;
  final String currencyCode;

  const SettlementEdge({
    required this.fromParticipantId,
    required this.toParticipantId,
    required this.amountMinor,
    required this.currencyCode,
  });

  @override
  int get hashCode =>
      fromParticipantId.hashCode ^
      toParticipantId.hashCode ^
      amountMinor.hashCode ^
      currencyCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettlementEdge &&
          runtimeType == other.runtimeType &&
          fromParticipantId == other.fromParticipantId &&
          toParticipantId == other.toParticipantId &&
          amountMinor == other.amountMinor &&
          currencyCode == other.currencyCode;
}
