// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Per–line-item assignees: each line is split equally among its assignees (no FX conversion).
/// Rows are produced for every (participant × currency) present in the bill; amounts may be zero.
List<SplitResult> calculateSplitAssigned({
  required List<AssignedReceiptLine> lines,
  required List<ParticipantRef> participants,
}) => RustLib.instance.api.crateApiSimpleCalculateSplitAssigned(
  lines: lines,
  participants: participants,
);

/// Maps a decimal UI amount to integer minor units for persistence (e.g. SQLite).
/// IDR/JPY/KRW: 1 minor = 1 unit; others: cents (10^-2).
PlatformInt64 amountToMinorUnits({
  required double amount,
  required String currencyCode,
}) => RustLib.instance.api.crateApiSimpleAmountToMinorUnits(
  amount: amount,
  currencyCode: currencyCode,
);

double minorUnitsToAmount({
  required PlatformInt64 minor,
  required String currencyCode,
}) => RustLib.instance.api.crateApiSimpleMinorUnitsToAmount(
  minor: minor,
  currencyCode: currencyCode,
);

/// Plain string for amount text fields (add/edit line).
String amountToInputText({
  required double amount,
  required String currencyCode,
}) => RustLib.instance.api.crateApiSimpleAmountToInputText(
  amount: amount,
  currencyCode: currencyCode,
);

class AssignedReceiptLine {
  final ReceiptItem item;

  /// Empty = all current participants split this line equally.
  final List<String> assigneeIds;

  const AssignedReceiptLine({required this.item, required this.assigneeIds});

  @override
  int get hashCode => item.hashCode ^ assigneeIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssignedReceiptLine &&
          runtimeType == other.runtimeType &&
          item == other.item &&
          assigneeIds == other.assigneeIds;
}

class ParticipantRef {
  final String id;
  final String displayName;

  const ParticipantRef({required this.id, required this.displayName});

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParticipantRef &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName;
}

class ReceiptItem {
  final String name;
  final double price;

  /// ISO 4217 code (e.g. IDR, USD).
  final String currencyCode;

  const ReceiptItem({
    required this.name,
    required this.price,
    required this.currencyCode,
  });

  @override
  int get hashCode => name.hashCode ^ price.hashCode ^ currencyCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiptItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          price == other.price &&
          currencyCode == other.currencyCode;
}

class SplitResult {
  final String personName;
  final double totalOwed;
  final String currencyCode;

  const SplitResult({
    required this.personName,
    required this.totalOwed,
    required this.currencyCode,
  });

  @override
  int get hashCode =>
      personName.hashCode ^ totalOwed.hashCode ^ currencyCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SplitResult &&
          runtimeType == other.runtimeType &&
          personName == other.personName &&
          totalOwed == other.totalOwed &&
          currencyCode == other.currencyCode;
}
